server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:demo #메모리 기반
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        '[default_batch_fetch_size]': 16

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
